on: push
name: tests
jobs:
  gym_mapf_ut:
    name: gym_mapf unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          build-type: Debug
      - run: ${{ runner.workspace }}/build/gym_mapf/tests/gym_mapf_ut

  solvers_ut:
    name: solvers unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          build-type: Debug
      - run: ${{ runner.workspace }}/build/solvers/tests/solvers_ut

  benchmark:
    name: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          build-type: Release
      - run: ${{ runner.workspace }}/build/main

  sanity_benchmark:
    name: sanity_benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          build-type: Release
      - run: ${{ runner.workspace }}/build/sanity_benchmark