on: push
name: tests
jobs:
  gym_mapf_ut:
    name: gym_mapf unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          build-type: Debug
      - run: ${{ runner.workspace }}/build/gym_mapf/tests/gym_mapf_ut

  solvers_ut:
    name: solvers unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          build-type: Debug
      - run: ${{ runner.workspace }}/build/solvers/tests/solvers_ut

  sanity_benchmark:
    name: sanity_benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          build-type: Release
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9 # Install the python version needed
      - run: python -m pip install --upgrade pip pandas==1.4.2
      - run: python -m pip install --upgrade pip tabulate==0.8.9
      - run: python results/sanity_benchmark.py ${{ runner.workspace }}/build/sanity_benchmark