on: push
name: tests
jobs:
  gym_mapf_ut:
    name: gym_mapf unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          build-type: Debug
      - run: ${{ runner.workspace }}/build/gym_mapf/gym_mapf_ut

  benchmark:
    name: benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          build-type: Release
      - run: ${{ runner.workspace }}/build/main